apiVersion: "security.cloud.ibm.com/v1"
kind:       OidcConfig
metadata:
  name:      oidc-provider-config
  namespace: sample-app
spec:
  authMethod:   client_secret_basic
  discoveryUrl: https://us-south.appid.cloud.ibm.com/oauth/v4/<tenant_id>/.well-known/openid-configuration
  clientId:     <client-id>
  clientSecret: <client-secret>
